FROM python:3.10-slim

WORKDIR /app


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


COPY . /app/
WORKDIR /app/src/slackbot

CMD [ "celery","-A","slackbot","worker","--loglevel=info" ]
