FROM  python:3.10-slim

WORKDIR /app

#Install dependencies 
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN pip show gunicorn

# copy the app code
COPY . /app/

WORKDIR /app/src/slackbot


EXPOSE 8080

CMD ["gunicorn", "slackbot.wsgi:application","--bind", "0.0.0.0:8000", ]
# CMD ["python", "manage.py","runserver","--bind", "8081"]


